#!/bin/bash

while getopts "hUu:" opt; do
   case $opt in
      h)
         printf "\n This script will regenerate the stand alone ansible playbook and (optionally) reset the  FQDN of the playbook \n\n  
         Usage ./utilities/playbook regen -uUh [<HOST_FQDN>] \n 
         MUST BE RUN FROM CLOUDSCHEDULER DIRECTORY\n\n
         OPTIONS: \n 
         -u <FQDN-of-host> Runs 'reset_standalone_hostname' and changes it to the FQDN entered, \n
         -U Rests host name to default 'csv2-cont.heprc.uvic.ca' \n
         -h Display these help messages and exit \n
         If no options are given you will be prompted to enter the FQDN of the host for the standalone \n\n\n" >&2
         exit 0
        ;;

      U)
         FQDN="csv2-cont.heprc.uvic.ca"
      ;;

      u)
            FQDN=$OPTARG
      ;;   
    esac
done

./utilities/regenerate_ansible_playbook
cd ansible-playbook
../utilities/reset_stand_alone_hostname $FQDN
