#!/bin/env python
###
### This command requires the heprc Inventory system.
###
from subprocess import Popen, PIPE
import os
import shutil
import sys

def syscmd (gvar, cmd, cwd=None):
    if cwd:
        p = Popen(cmd, cwd=cwd, stdout=PIPE, stderr=PIPE)
    else:
        p = Popen(cmd, stdout=PIPE, stderr=PIPE)

    stdout, stderr = p.communicate()
    if p.returncode != 0:
        print(stdout)
        print(stderr)
        raise Exception('Cmd=%s, RC=%s.' % (cmd, p.returncode))

    return p.returncode, stdout, stderr

gvar = {}
gvar['cmd_path'] = os.path.realpath(sys.argv[0])
gvar['bread_crumbs'] = gvar['cmd_path'].split('/')
gvar['bread_crumbs_ix'] = gvar['bread_crumbs'].index('cloudscheduler')
gvar['root_dir'] = '/'.join(gvar['bread_crumbs'][:gvar['bread_crumbs_ix']])

syscmd(gvar, ['.bin/ansible_util', '-S', '%s/cloudscheduler/ansible-playbook' % gvar['root_dir'], 'csv2-sa'], cwd='%s/Inventory/heprc' % gvar['root_dir'])

os.remove('%s/cloudscheduler/ansible-playbook/inventory' % gvar['root_dir'])
shutil.rmtree('%s/cloudscheduler/ansible-playbook/inventory_host_variables' % gvar['root_dir'])
os.remove('%s/cloudscheduler/ansible-playbook/staticvms.yaml' % gvar['root_dir'])
os.remove('%s/cloudscheduler/ansible-playbook/roles/csv2/vars/csv2-default-vars.yaml' % gvar['root_dir'])
os.remove('%s/cloudscheduler/ansible-playbook/roles/csv2/vars/csv2-sa-vars.yaml' % gvar['root_dir'])
os.remove('%s/cloudscheduler/ansible-playbook/roles/csv2/vars/csv2-sa-secrets.yaml' % gvar['root_dir'])

shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/addenda' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/roles/csv2/vars/addenda' % gvar['root_dir'])
shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/README.md' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/README.md' % gvar['root_dir'])
shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/inventory' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/inventory' % gvar['root_dir'])
shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/csv2-sa.yaml' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/csv2-sa.yaml' % gvar['root_dir'])
shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/csv2-default-vars.yaml' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/csv2-default-vars.yaml' % gvar['root_dir'])
shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/csv2-sa-vars.yaml' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/csv2-sa-vars.yaml' % gvar['root_dir'])
shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/csv2-sa-secrets.yaml' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/csv2-sa-secrets.yaml' % gvar['root_dir'])
shutil.copyfile('%s/cloudscheduler/.ansible-playbook-templates/csv2-container-build.yaml' % gvar['root_dir'], '%s/cloudscheduler/ansible-playbook/csv2-container-build.yaml' % gvar['root_dir'])

os.symlink('../../../csv2-default-vars.yaml', '%s/cloudscheduler/ansible-playbook/roles/csv2/vars/csv2-default-vars.yaml' % gvar['root_dir'])
os.symlink('../../../csv2-sa-vars.yaml', '%s/cloudscheduler/ansible-playbook/roles/csv2/vars/csv2-sa-vars.yaml' % gvar['root_dir'])
os.symlink('../../../csv2-sa-secrets.yaml', '%s/cloudscheduler/ansible-playbook/roles/csv2/vars/csv2-sa-secrets.yaml' % gvar['root_dir'])
