#!/usr/bin/env python3
import os
import sys

counter = 0
if len(sys.argv) > 1 and os.path.isfile(sys.argv[1]):
    fd = open(sys.argv[1])
    lines = fd.read().split('\n')
    fd.close()

    for line in lines:
        pre = line.split('lno(', 1)
        if len(pre) > 1:
            post =  pre[1].split(')', 1)
            print("%slno('%s%02d')%s" % (pre[0], post[0][1:3], counter, post[1]))
            counter += 1

        else:
            print(line)
else:
    print('Synopsis: resequence_error_codes <file_path.py>')
 
