#!/bin/env python3
from subprocess import Popen, PIPE
import os
import shutil
import sys

def syscmd (gvar, cmd, cwd=None):
    if cwd:
        p = Popen(cmd, cwd=cwd, stdout=PIPE, stderr=PIPE)
    else:
        p = Popen(cmd, stdout=PIPE, stderr=PIPE)

    stdout, stderr = p.communicate()
    if p.returncode != 0:
        print(stdout)
        print(stderr)
        raise Exception('cwd=%s, cmd=%s, RC=%s, stderr=%s' % (cwd, cmd, p.returncode, stderr))

    return p.returncode, stdout, stderr

fqdn = input('Please enter the FQDN of the host you wish to build for CSV2? ')
words = fqdn.split('.')
domain = '.'.join(words[1:])
hostname = words[0]

gvar = {}
gvar['cmd_path'] = os.path.realpath(sys.argv[0])
gvar['bread_crumbs'] = gvar['cmd_path'].split('/')
gvar['bread_crumbs_ix'] = gvar['bread_crumbs'].index('cloudscheduler')
gvar['root_dir'] = '/'.join(gvar['bread_crumbs'][:gvar['bread_crumbs_ix']+1])

syscmd(gvar, ['sed', '-i', 's/csv2-sa/%s/' % hostname, 'addenda'], cwd='%s/ansible-playbook' % gvar['root_dir'])

syscmd(gvar, ['sed', '-i', 's/csv2-sa/%s/' % hostname, 'README'], cwd='%s/ansible-playbook' % gvar['root_dir'])

syscmd(gvar, ['mv', 'csv2-sa-secrets.yaml', '%s-secrets.yaml' % hostname], cwd='%s/ansible-playbook' % gvar['root_dir'])

syscmd(gvar, ['sed', '-i', 's/csv2-sa-myadmin.heprc.uvic.ca/%s-myadmin.%s/' % (hostname, domain), 'csv2-sa-vars.yaml'], cwd='%s/ansible-playbook' % gvar['root_dir'])
syscmd(gvar, ['sed', '-i', 's/csv2-sa.heprc.uvic.ca/%s/' % fqdn, 'csv2-sa-vars.yaml'], cwd='%s/ansible-playbook' % gvar['root_dir'])
syscmd(gvar, ['sed', '-i', 's/csv2-sa/%s/' % hostname, 'csv2-sa-vars.yaml'], cwd='%s/ansible-playbook' % gvar['root_dir'])
syscmd(gvar, ['mv', 'csv2-sa-vars.yaml', '%s-vars.yaml' % hostname], cwd='%s/ansible-playbook' % gvar['root_dir'])

syscmd(gvar, ['mv', 'csv2-sa.yaml', '%s.yaml' % hostname], cwd='%s/ansible-playbook' % gvar['root_dir'])

syscmd(gvar, ['sed', '-i', 's/csv2-sa.heprc.uvic.ca/%s/' % fqdn, 'inventory'], cwd='%s/ansible-playbook' % gvar['root_dir'])

