#!/bin/bash
    pw_line=$(grep db_password /etc/cloudscheduler/cloudscheduler.yaml)
    pw_words=($pw_line)
    echo
    date
    echo
    mysql -ucsv2 -p${pw_words[1]:1:-1} -t -e "select 'resources',group_name,cloud_name,default_keep_alive,flavor,flavor_cores,flavor_disk,flavor_ram,flavor_swap,flavor_slots,VMs,VMs_manual,VMs_in_error,VMs_starting,VMs_unregistered,VMs_idle,VMs_running from view_available_resources where VMs>0; select 'jobs',group_name,target_clouds as targets,instance_type as flavor,concat(request_cpus_min, '/', request_cpus_max, '/', request_cpus_total) as request_cpu,concat(request_disk_min, '/', request_disk_max, '/', request_disk_total) as request_disk,concat(request_ram_min, '/', request_ram_max, '/', request_ram_total) as request_ram,concat(request_swap_min, '/', request_swap_max, '/', request_swap_total) as request_swap,flavors,idle,running,completed,held from view_groups_of_idle_jobs;" csv2
