#!/bin/bash
function update {
    clear
    cat ${tmp}/p0
    cat ${tmp}/p1
    cat ${tmp}/p3

    cat ${tmp}/p0 >> /tmp/watch_csv2_${SUDO_USER}.log
    cat ${tmp}/p1 >> /tmp/watch_csv2_${SUDO_USER}.log
    cat ${tmp}/p3 >> /tmp/watch_csv2_${SUDO_USER}.log
    mv -f ${tmp}/p1 ${tmp}/p2
}
    tmp=$(mktemp -d)
    IFS='"' read -r -a pw <<< $(grep db_password /etc/cloudscheduler/cloudscheduler.yaml)

    while true; do
        mysql -u csv2 -p${pw[1]} -t csv2 -e 'select unix_timestamp();' > ${tmp}/p0

        echo -e '\n--- condor_jobs -------------------------' > ${tmp}/p1
        mysql -u csv2 -p${pw[1]} -t csv2 -e 'select request_cpus,request_disk div (1024*1024) as request_disk,request_ram,sum(case when job_status=1 then 1 else 0 end) as idle,sum(case when job_status=5 then 1 else 0 end) as held,sum(case when job_status!=1 and job_status!=5 then 1 else 0 end) as other from condor_jobs group by request_cpus,request_disk,request_ram;' >> ${tmp}/p1

        echo -e '\n--- view_groups_of_idle_jobs ------------' >> ${tmp}/p1
        mysql -u csv2 -p${pw[1]} -t csv2 -e 'select group_name,job_per_core,request_cpus_max,request_cpus_total,request_disk_max,request_disk_total,request_ram_max,request_ram_total,request_swap_max,request_swap_total,idle,running,completed,held,other,flavors from view_groups_of_idle_jobs;' >> ${tmp}/p1

        echo -e '\n--- view_available_resources ------------' >> ${tmp}/p1
        mysql -u csv2 -p${pw[1]} -t csv2 -e 'select group_name,flavor,flavor_slots,flavor_cores,flavor_disk,flavor_ram,flavor_swap,flavor_VMs,flavor_manual,flavor_error,flavor_retiring from view_available_resources;' >> ${tmp}/p1

        echo -e '\n--- condor_machines ---------------------' >> ${tmp}/p1
        mysql -u csv2 -p${pw[1]} -t csv2 -e 'select machine,slot_type from condor_machines;' >> ${tmp}/p1

        echo -e '\n--- csv2_vms ----------------------------' >> ${tmp}/p1
        mysql -u csv2 -p${pw[1]} -t csv2 -e 'select cv.group_name,cv.cloud_name,cf.name as flavor,hostname,htcondor_partitionable_slots,htcondor_dynamic_slots,htcondor_slots_timestamp,retire,terminate,status_changed_time,cv.last_updated from csv2_vms as cv left outer join cloud_flavors as cf on cv.group_name=cf.group_name and cv.cloud_name=cf.cloud_name and cv.flavor_id=cf.id;' >> ${tmp}/p1

        echo -e '\n--- view_idle_vms -----------------------' >> ${tmp}/p1
        mysql -u csv2 -p${pw[1]} -t csv2 -e 'select * from view_idle_vms;' >> ${tmp}/p1

        condor_q -allusers > ${tmp}/p3

        if [ -e ${tmp}/p2 ]; then
            diff -q ${tmp}/p1 ${tmp}/p2 
            if [ $? == 1 ]; then
                update
            else
                echo "No change." >>/tmp/watch_csv2_${SUDO_USER}.log
            fi
        else
            update
        fi
        sleep 10
    done
