.so ../man/_header.so
\fBcloudscheduler metadata list\fR \- list group metadata from cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B metadata
.B list
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_metadata_list.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_metadata_name.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options_except_with.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
Listing group metadata for the group "example":
.EX
$ cloudscheduler metadata list
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

Active Group/Metadata:
+---------+-------------------+---------+----------+--------------+
+ Group   | Metadata Filename | Enabled | Priority | MIME Type    +
+---------+-------------------+---------+----------+--------------+
| example | example.yaml      | 1       | 0        | cloud-config |
| example | testing.yaml      | 0       | 5        | cloud-config |
+---------+-------------------+---------+----------+--------------+
Rows: 2
.EE
.TP
2.
Listing group metadata "example":
.EX
$ cloudscheduler metadata list -mn example.yaml
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

Active Group/Metadata:
+---------+-------------------+---------+----------+--------------+
+ Group   | Metadata Filename | Enabled | Priority | MIME Type    +
+---------+-------------------+---------+----------+--------------+
| example | example.yaml      | 1       | 0        | cloud-config |
+---------+-------------------+---------+----------+--------------+
Rows: 1
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_group_metadata-list (1)
.BR csv2_metadata_group-defaults (1)
.BR csv2_metadata_delete (1)
.BR csv2_metadata_edit (1)
.BR csv2_metadata_load (1)
.BR csv2_metadata_update (1)
