.so ../man/_header.so
\fBcloudscheduler my\fR \- change or display the settings of the current user on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B my
.I action
.I mandatory_parameters
.RI "[" "options " "...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_my.so
.\" --------------------------------------------------------------------
.SH ACTIONS
.\" --------------------------------------------------------------------
For information on the parameters associated with each \fBmy\fR action, refer to the documentation for that action (\fBcloudscheduler my \fIaction\fB -H\fR). The following actions are available for the \fBmy\fR object:
.TP
.B settings
.so ../man/descriptions/_my_settings.so
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_my_settings (1)
