.so ../man/_header.so
\fBcloudscheduler cloud metadata_collation\fR \- collate cloud and group metadata lists for cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B cloud
.B metadata-collation
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_cloud_metadata_collation.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_cloud_name.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
List all metadata that would be applied to VMs on the cloud "example":
.EX
$ cloudscheduler cloud metadata_collation -cn example
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_cloud (1)
.BR csv2_cloud_add (1)
.BR csv2_cloud_delete (1)
.BR csv2_cloud_list (1)
.BR csv2_cloud_metadata_delete (1)
.BR csv2_cloud_metadata_edit (1)
.BR csv2_cloud_metadata_list (1)
.BR csv2_cloud_metadata_load (1)
.BR csv2_cloud_metadata_update (1)
.BR csv2_cloud_status (1)
.BR csv2_cloud_update (1)
