.so ../man/_header.so
\fBcloudscheduler image list\fR \- list openstack images on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B image
.B list
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_image_list.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_group_name.so
.so ../man/parameters/_cloud_name.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
List all openstack images for the active group:
.EX
$ cloudscheduler image list
Server: default, Active User: example, Active Group: exampleA, User's Groups: ['exampleA']

Images:
+-----------+---------+-------------+-----------------------------------------+---------------------+----------------------------------+
+           |         |             |                                            Image Info                                            +
+   Group   |  Cloud  |    rank     |                  Name                        Creation Date                  Checksum             +
+-----------+---------+-------------+-----------------------------------------+---------------------+----------------------------------+
| exampleA  | ex_cldA | 199         | CentOS 6.5                              | 2014-06-20 14:21:08 | 20df8856922d57e172a6807b2dc1b499 |
| exampleA  | ex_cldB | 200         | CentOS 7                                | 2017-04-24 17:03:31 | 288467b7d5f739b7d4e95fc3225f08e2 |
+-----------+---------+-------------+-----------------------------------------+---------------------+----------------------------------+
Rows: 2
.EE
.TP
2.
List a specific cloud "example":
.EX
$ cloudscheduler image list -cn ex_cldB
Server: default, Active User: example, Active Group: exampleA, User's Groups: ['exampleA']

Images:
+-----------+---------+-------------+-----------------------------------------+---------------------+----------------------------------+
+           |         |             |                                            Image Info                                            +
+   Group   |  Cloud  |    rank     |                  Name                        Creation Date                  Checksum             +
+-----------+---------+-------------+-----------------------------------------+---------------------+----------------------------------+
| exampleA  | ex_cldB | 200         | CentOS 7                                | 2017-04-24 17:03:31 | 288467b7d5f739b7d4e95fc3225f08e2 |
+-----------+---------+-------------+-----------------------------------------+---------------------+----------------------------------+
Rows: 1
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_image_list (1)
.BR csv2_image_transfer (1)
.BR csv2_image_delete (1)
.BR csv2_image_upload (1)
