.so ../man/_header.so
\fBcloudscheduler job list\fR \- list jobs on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B job
.B list
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_job_list.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_job_hold.so
.so ../man/parameters/_job_id.so
.so ../man/parameters/_job_image.so
.so ../man/parameters/_job_priority.so
.so ../man/parameters/_job_requirements.so
.so ../man/parameters/_job_request_cpus.so
.so ../man/parameters/_job_request_disk.so
.so ../man/parameters/_job_request_ram.so
.so ../man/parameters/_job_request_swap.so
.so ../man/parameters/_job_status.so
.so ../man/parameters/_job_target_alias.so
.so ../man/parameters/_job_user.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options_except_with.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
List all jobs for the current group:
.EX
$ cloudscheduler job list
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

Jobs (1/6)
+---------+--------+------------+------------+---------------------+-----------+--------------+
+ Group   | Job ID | Cluster ID | Process ID | User                | User Data | Requirements +
+---------+--------+------------+------------+---------------------+-----------+--------------+
| example | 1      | 1          | 1          | example@example.com | None      | None         |
| example | 2      | 2          | 1          | example@example.com | None      | None         |
+---------+--------+------------+------------+---------------------+-----------+--------------+

Jobs (2/6)
+---------+--------+---------------+---------+---------------+-----------+-----------+
+         |        |               |         |               |       Requested       +
+ Group   | Job ID | Target Clouds | Cloud   | Instance Type |   CPUs      RAM {MBs} +
+---------+--------+---------------+---------+---------------+-----------+-----------+
| example | 1      | example       | example | example       | 4         | 1000      |
| example | 2      | example       | example | example       | 4         | 1000      |
+---------+--------+---------------+---------+---------------+-----------+-----------+

Jobs (3/6)
+---------+--------+------------+------------+---------------+-------+---------+----------+
+         |        |        Requested        |               |       |         |   Job    +
+ Group   | Job ID | Disk {GBs}   Swap (GBs) | Jobs per Core | Image | Network | Priority +
+---------+--------+------------+------------+---------------+-------+---------+----------+
| example | 1      | 5          | 0          | 1             | None  | None    | 0        |
| example | 2      | 5          | 0          | 1             | None  | None    | 0        |
+---------+--------+------------+------------+---------------+-------+---------+----------+

Jobs (4/6)
+---------+--------+-------------+------------------+------------------+------------------+
+         |        |     Job     |                    Job Status Flags                    +
+ Group   | Job ID | Status Code |       Idle             Running           Completed     +
+---------+--------+-------------+------------------+------------------+------------------+
| example | 1      | 2           | 0                | 1                | 0                |
| example | 2      | 2           | 0                | 1                | 0                |
+---------+--------+-------------+------------------+------------------+------------------+

Jobs (5/6)
+---------+--------+------------------+------------------+----------------------+
+         |        |          Job Status Flags           |                      +
+ Group   | Job ID |       Held              Other       | Keep Alive (seconds) +
+---------+--------+------------------+------------------+----------------------+
| example | 1      | 0                | 0                | 0                    |
| example | 2      | 0                | 0                | 0                    |
+---------+--------+------------------+------------------+----------------------+

Jobs (6/6)
+---------+--------+----------------+---------------------+---------------------+-----------------+
+ Group   | Job ID | Max Spot Price | State Change Date   | Queued Date         | Held Job Reason +
+---------+--------+----------------+---------------------+---------------------+-----------------+
| example | 1      | 0              | 2018-08-23 00:00:00 | 2018-08-23 00:00:00 | None            |
| example | 2      | 0              | 2018-08-23 00:00:00 | 2018-08-23 00:00:00 | None            |
+---------+--------+----------------+---------------------+---------------------+-----------------+
Rows: 2
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_job (1)
.BR csv2_job_update (1)
