.ig
csv2.man

Copyright (C) 2018
University of Victoria
Written in 2018 by Colin Leavett-Brown <crlb@uvic.ca>

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with the
Invariant Sections being this .ig-section and AUTHOR, with no
Front-Cover Texts, and with no Back-Cover Texts.

..
.
.
.\" --------------------------------------------------------------------
.\" Environment variable
.de EnvVar
.  SM
.  BR \%\\$1 \\$2
..
.\" --------------------------------------------------------------------
.\" `char or string'
.de Quoted
.  ft CR
\[oq]\\$*\[cq]
.  ft
..
.
.\" --------------------------------------------------------------------
.\" Title
.\" --------------------------------------------------------------------
.
.TH csv2 1 "28 February 2018" "cloudscheduler version 2"
.SH NAME
\fBcsv2\fP \- command line interface to cloudscheduler version 2 (csv2).
.
.
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.
.SY csv2
.B config
.B delete
.BI \-s\  server
.
.SY csv2
.B config
.B list
.
.SY csv2
.B config
.B set
.BI \-s\  server
.OP \-C target-common-name
.OP \-c cert
.OP \-g group
.OP \-h
.OP \-k key
.OP \-R
.OP \-P target-password
.OP \-p password
.OP \-S url
.OP \-U target-user
.OP \-u user
.OP \-y
.

.SY csv2
.B user
.B create
.BI \-C\ target-common-name
.BI \-P\ target-password
.BI \-U\ target-user
.RI [ authentication-options\~ .\|.\|.]
.
.SY csv2
.B user
.B delete
.BI \-U\ target-user
.RI [ authentication-options\~ .\|.\|.]
.
.SY csv2
.B user
.B list
.RI [ authentication-options\~ .\|.\|.]
.

.YS
.
.
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.
The \fBcsv2\fP command line interface makes RESTful requests to csv2 servers to retrieve information and to modify settings.
Since the command can communicate with any number of servers, all of which require user identification, options are provided to address the server together with the necessary credentials.
These and other options can be saved (see \fBconfig\fP in \fBOBJECTS and ACTIONS\fP below) to reduce repetative typing.

Information retrieved is displayed in tabular form much like that produced by an SQL select statement.
Sometimes, when the rows of information are long enough to cause line wrapping, these tables can be difficult to read.
The \fB--rotate\fP option is provided to present the information in two columns (key/value) to improve readability. 

When \fBcsv2\fP is used to modify the settings of a server, the command merely returns confirmation of success or failure.

The command may issue prompts in the following cases: when password prompts are requested (see \fB--password\fP and \fB--target-password\fP below) and when confirmation of a change is required (see \fB--yes\fP below).

.
.
.\" --------------------------------------------------------------------
.SH OBJECTS and ACTIONS
.\" --------------------------------------------------------------------
.P
The first two positional arguments to the \fBcsv2\fP command are  an \fBobject\fP 
and an \fBaction\fP to be perfomed.
The \fBobjects\fP and their associated \fBactions\fP are summarized here:
.

.TP
.BI config
This object manipulates user settings within a user's 
.B \:~/.csv2
directory, and provides actions to save, update, and delete settings for multiple servers.
The following actions are defined:
.
.RS
.RS
.TP
.BI delete
- Removes the settings associated with a particular server. 
As such, the 
.OP \-s server
is always required.
.
.TP
.BI list
- Lists all saved settings in tabular format.
The \fB[\-R]\fP option may be used to rotate the table and improve readability.
.
.TP
.BI set
- Is used create and update settings for a server. 
As such, the 
.OP \-s server
is always required.
This action accepts any of the options listed under \fBOPTIONS\fP
.
.
.RE
.RE
.TP
.BI user
This object manipulates user objects on csv2 servers. 
In addition to the options specific to a task, all of the actions for this 
object require \fBAuthentication Options\fP (see below).
The following actions are defined:
.
.
.RS
.RS
.TP
.BI create
- This action creates a new csv2 user on the addressed server.
The following options are mandatory:
\fB[\-C\ target-common-name]\fP,
\fB[\-P\ target-password]\fP, and
\fB[\-U\ target-user]\fP.
.
.TP
.BI delete
- This action removes a csv2 user from the addressed server.
The`
\fB[\-U\ target-user]\fP.
option is mandatory.
This action will prompt for confirmation unless the \fB[-y]\fP has been employed.
.
.TP
.BI list
- Lists all csv2 users defined on a server.
The \fB[\-R]\fP option may be used to rotate the table and improve readability.
.
.TP
.BI update
- This action updates the csv2 user definition on a server. 
Only the \fB[-U target-user]\fP option is required, though other user options should be specified 
to update the appropriate attributes.
.

.
.
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.P
The \fBcsv2\fP command line options are divided into the following catagories: 
.
.\" --------------------------------------------------------------------
.SS Authentication Options
.\" --------------------------------------------------------------------
.
The following options are used to address the csv2 server and to identify the user to the server:
.
.TP
.OP \-S\ \:|\ --url url
Specifies the HTTPS protocol location of the csv2 server. The default URL is https://localhost.
.
.TP
.OP \-c\ \:|\ --cert cert
Specifies the location of an x509 grid certificate used to identify the user to the csv2 server.
There is no default.
If specified, the user must also specify the 
.OP \-k key
option, in which case certificate authentication will be used and the
.OP \-u user
and the
.OP \-p password
options will be ignored.
.
.TP
.OP \-k\ \:|\ --key key
Specifies the location of an x509 grid certificate key used to identify the user to the csv2 server.
There is no default.
If specified, the user must also specify the 
.OP \-c cert
option, in which case certificate authentication will be used and the
.OP \-u user
and the
.OP \-p password
options will be ignored.
.
.TP
.OP \-u\ \:|\ --user user
Specifies the user ID to use when authenticating with the csv2 server.
There is no default.
If specified, the user must also specify the 
.OP \-p password
option, or a password promp will be issued.
This option, together with the
.OP \-p password
option will be ignored if certificate authentication is being used.
.
.TP
.OP \-p\ \:|\ --password password
Specifies the password to use when authenticating with the csv2 server.
If user/password authentication is being used and no password is provided, a password prompt will be issued.
This option, together with the
.OP \-u user
option will be ignored if certificate authentication is being used.
.
.TP
In summary, the user must provide either of the following when communicating with a csv2 server:
.
.RS
.TP
.BI *
[ \fB\:-S\fP \fIurl\fP ], [ \fB\:-c\fP \fIcert\fP ], and [ \fB\:-k\fP \fIkey\fP ], or
.TP
.BI *
[ \fB\:-S\fP \fIurl\fP ], [ \fB\:-u\fP \fIuser\fP ], and [ \fB\:-p\fP \fIpassword\fP ]
.RE
.
.
.TP
However, if the [ \fB\-S\fP \fIurl\fP ] option is omitted, a default URL of https://localhost will be used.
.
.\" --------------------------------------------------------------------
.SS Attribute Options
.\" --------------------------------------------------------------------
.
The following options are used to set attributes on  csv2 servers:
.
.TP
.OP \-C\ \:|\ --target-common-name target-common-name
Specifies a csv2 user's common name to match with their grid certificate during user authentication.
.
.TP
.OP \-g\ \:|\ --group group
Specifies a csv2 group to which other attributes are attached.
.
.TP
.OP \-P\ \:|\ --target-password target-password
Specifies a csv2 user's password when defining or updating csv2 user attributes.
If the value specified is a period ("."), the \fBcsv2\fP command will prompt for the target-password
when necessary.
.
.TP
.OP \-U\ \:|\ --target-user target-user
Specifies a csv2 user ID when defining or updating csv2 user attributes.
.
.
.\" --------------------------------------------------------------------
.SS Boolean Options
.\" --------------------------------------------------------------------
.
All boolean options have a default value of \fBFalse\fP. Each specification of a boolean option
inverts its' current value; this is of particular importance when considering saved 
settings (see \fBConfiguration Option\fP below).
.
.TP
.OP \-h\ \:|\ --help
When set to \fBTrue\fP, this switch will direct the user to this csv2 man page.
.
.TP
.OP \-R\ \:|\ --rotate
This option determines the orientation of output tables.
Many queries result in tables with many columns which can be difficult to read when line wrapping occurs.
When set to \fBTrue\fP, this switch will present tables in two columns of key/value pairs.
.
.TP
.OP \-y\ \:|\ --yes
This option determines whether confirmation of specific actions are required (see specific \fBobject/action\fP for applicability).
When set to \fBFalse\fP, actions requiring confirmation will issue prompts and will only continue with a repons of \fByes\fP. When set to \fBTrue\fP, no confirmation prompts will be issued and actions will assume confirmation has already been given.
.
.\" --------------------------------------------------------------------
.SS Configuration Option
.\" --------------------------------------------------------------------
.
All of the above options can be saved as a collection of settings for one or more servers.
Saved settings can be unset by specifying a value of a single dash ("-").
However, no boolean value can be unset. Instead, boolean values can be inverted by repetative specification, like a toggle switch.
By default, a \fBdefault\fP server settings collection is created with minimal options if it doesn't already exist
because it is required during option processing which proceeds as follows:
.
.RS
.TP
.BI *
All command line arguments are scanned and saved in a temporary dictionary.
.
.TP
.BI *
If the [ \fB\:-s\fP \fIserver\fP ] option is present, the specified server settings are loaded into the current command settings.
Otherwise, the \fBdefault\fP server settings are loaded into the current command settings.
.
.TP
.BI *
The remaining command line options are applied to the current command settings.
.
.TP
.BI *
Control is then passed to the current \fBobject/action\fP.
.RE
.
.TP
There is only one configuration option as follows:
.
.TP
.OP \-s\ \:|\ --server server
Specifies the server settings to be loaded during option processing.
If omitted, the \fBdefault\fP server settings collection is loaded.
When used with the \fBcsv2 config set\fP command, this parameter causes
all current options and settings for the specified server to be written to the 
user's home directory at \fB\:~/.csv2/<server>/settings.yaml\fP.
.
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.
.BI 1.
Configure the default server location, authenticate using my user ID, but always prompt for
passwords, even when setting up new user passwords. When I query attributes, I would like tables
rotated.
.
.RS
.TP
csv2 config set -s default -S https://csv2.heprc.uvic.ca -u crlb -P . -R
.RE
.
.TP
.BI 2.
Configure a second server to use certificate authentication.
.
.RS
.TP
csv2 config set -s belle -S https://bellecs.heprc.uvic.ca -c ~/grid-security/usercert.pem
-k ~/grid-security/userkey.pem -P . -R
.RE
.
.TP
.BI 3.
Query the csv2 users on csv2 and on belle. The command will prompt for my password for csv2 but not for belle.
.
.RS
.TP
csv2 user list
.TP
csv2 user list -s belle
.RE
.
.
.TP
.BI 4.
Create a new csv2 user on belle. The command will prompt for the new (target) user's password.
.
.RS
.TP
csv2 user create -s belle -U fishy -C 'fish and chips'
.RE
.
