.so ../man/_header.so
\fBcloudscheduler job\fR \- manage jobs on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B job
.I action
.I mandatory_parameters
.RI "[" "options " "...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_job.so
.\" --------------------------------------------------------------------
.SH ACTIONS
.\" --------------------------------------------------------------------
For information on the parameters associated with each \fBjob\fR action, refer
to the documentation for that action (\fBcloudscheduler group \fIaction\fB -H\fR).
The following actions are available for the \fBjob\fR object:
.TP
.B list
.so ../man/descriptions/_job_list.so
.TP
.B update
.so ../man/descriptions/_job_update.so
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_job_list (1)
.BR csv2_job_update (1)
