.so ../man/_header.so
\fBcloudscheduler server config\fR \- modify and view configuration of cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B server
.B config
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_server_config.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_config_category.so
.so ../man/parameters/_config_key_values.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options_except_with.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH CONFIGURATION CATEGORIES AND OPTIONS
.\" --------------------------------------------------------------------
.\" ../man/configuration/_csjobs.py.so
.so ../man/configuration/_csmachines.py.so
.so ../man/configuration/_csmain.so
.so ../man/configuration/_csstatus.py.so
.so ../man/configuration/_csv2-ec2-instance-types.so
.so ../man/configuration/_csv2-ec2-regions.so
.so ../man/configuration/_ec2cloudPoller.py.so
.so ../man/configuration/_ec2FlavorPoller.py.so
.so ../man/configuration/_ec2_image_filter.so
.so ../man/configuration/_ec2_instance_type_filter.so
.so ../man/configuration/_general.so
.so ../man/configuration/_glintPoller.py.so
.so ../man/configuration/_openstackPoller.py.so
.so ../man/configuration/_signal_manager.so
.so ../man/configuration/_SQL.so
.so ../man/configuration/_startd_errors.py.so
.so ../man/configuration/_timeseriesPoller.py.so
.so ../man/configuration/_watch_csv2.so
.so ../man/configuration/_web_frontend.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
Viewing server configuration:
.EX
$ cloudscheduler server config
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

Server Configuration:
+--------------+--------------+------+--------------------------------------+
+ Category     | Config Key   | Type | Value                                +
+--------------+--------------+------+--------------------------------------+
| web_frontend | enable_glint | bool | False                                |
| web_frontend | log_file     | str  | /var/log/cloudscheduler/csv2_web.log |
+--------------+--------------+------+--------------------------------------+
Rows: 2
.EE
.TP
2.
Updating the config for the server:
.EX
$ cloudscheduler server config -cc web_frontend -eg True -lf /var/log/cloudscheduler/csv2_web_updated.log
server config successfully updated.
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

Server Configuration:
+--------------+--------------+------+----------------------------------------------+
+ Category     | Config Key   | Type | Value                                        +
+--------------+--------------+------+----------------------------------------------+
| web_frontend | enable_glint | bool | True                                         |
| web_frontend | log_file     | str  | /var/log/cloudscheduler/csv2_web_updated.log |
+--------------+--------------+------+----------------------------------------------+
Rows: 2
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_server (1)
