.so ../man/_header.so
\fBcloudscheduler group add\fR \- add groups to cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B group
.B add
.BI \-htcf " htcondor-central-manager-fqdn"
.BI \-gn " name"
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_group_add.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Mandatory
.\" --------------------------------------------------------------------
.so ../man/_mandatory_parameters.so
.so ../man/parameters/_htcondor_fqdn.so
.so ../man/parameters/_group_name.so
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_htcondor_container_hostname.so
.so ../man/parameters/_htcondor_other_submitters.so
.so ../man/parameters/_job_cores.so
.so ../man/parameters/_job_disk.so
.so ../man/parameters/_job_ram.so
.so ../man/parameters/_job_swap.so
.so ../man/parameters/_group_public_visibility.so
.so ../man/parameters/_username_group_add.so
.so ../man/parameters/_vm_flavor.so
.so ../man/parameters/_vm_image.so
.so ../man/parameters/_vm_keep_alive.so
.so ../man/parameters/_vm_keyname.so
.so ../man/parameters/_vm_network.so
.so ../man/parameters/_vm_security_groups.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
Adding the group "example":
.EX
$ cloudscheduler group add -htcf example.com -gn example
group "example" successfully added.
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_group (1)
.BR csv2_group_defaults (1)
.BR csv2_group_delete (1)
.BR csv2_group_list (1)
.BR csv2_group_metadata-delete (1)
.BR csv2_group_metadata-edit (1)
.BR csv2_group_metadata-list (1)
.BR csv2_group_metadata-load (1)
.BR csv2_group_metadata-save (1)
.BR csv2_group_metadata-update (1)
.BR csv2_group_update (1)
