.so ../man/_header.so
\fBcloudscheduler cloud add\fR \- add cloud definitions to cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B cloud
.B add
.BI "\-ca " "address"
.BI "\-cn " "name"
.BI "\-cpw " "password"
.BI "\-cp " "project"
.BI "\-cr " "region"
.BR "\-ct " "[" "amazon" " | " "azure" " | " "google" " | " "local" " | " "opennebula" " | " "openstack" "]"
.BI "\-cu " "user"
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_cloud_add.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Mandatory
.\" --------------------------------------------------------------------
.so ../man/_mandatory_parameters.so
.so ../man/parameters/_cloud_address.so
.so ../man/parameters/_cloud_name.so
.so ../man/parameters/_cloud_password.so
.so ../man/parameters/_cloud_project.so
.so ../man/parameters/_cloud_region.so
.so ../man/parameters/_cloud_type.so
.so ../man/parameters/_cloud_user.so
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_vm_boot_volume_type.so
.so ../man/parameters/_vm_boot_volume_size.so
.so ../man/parameters/_vm_boot_volume_per_core.so
.so ../man/parameters/_cloud_enabled.so
.so ../man/parameters/_cloud_priority.so
.so ../man/parameters/_cloud_project_domain.so
.so ../man/parameters/_cloud_project_domain_id.so
.so ../man/parameters/_cloud_spot_price.so
.so ../man/parameters/_cloud_user_domain.so
.so ../man/parameters/_cloud_user_domain_id.so
.so ../man/parameters/_group_metadata_exclusion.so
.so ../man/parameters/_vm_boot_volume.so
.so ../man/parameters/_vm_cores.so
.so ../man/parameters/_vm_flavor.so
.so ../man/parameters/_vm_image.so
.so ../man/parameters/_vm_keyname.so
.so ../man/parameters/_vm_keep_alive.so
.so ../man/parameters/_vm_ram.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
Adding the cloud "example":
.EX
$ cloudscheduler cloud add -ca example.ca -cn example -cpw example -cp example -cr example -ct amazon -cu example
cloud "example::example" successfully added.
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_cloud (1)
.BR csv2_cloud_delete (1)
.BR csv2_cloud_list (1)
.BR csv2_cloud_metadata-collation (1)
.BR csv2_cloud_metadata-delete (1)
.BR csv2_cloud_metadata-edit (1)
.BR csv2_cloud_metadata-list (1)
.BR csv2_cloud_metadata-load (1)
.BR csv2_cloud_metadata-save (1)
.BR csv2_cloud_metadata-update (1)
.BR csv2_cloud_status (1)
.BR csv2_cloud_update (1)
