.so ../man/_header.so
\fBcloudscheduler user list\fR \- list users from cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B user
.B list
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_user_list.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_username_list.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options_except_with.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
Viewing the user list filtered by username:
.EX
$ cloudscheduler user list -un example
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

Users:
+----------+--------------+--------------+-----------------+---------------+-------------+------------+
+ Username | Common Name  | Active Group | User Groups     | Not In Groups | Super User  | Joined     +
+----------+--------------+--------------+-----------------+---------------+-------------+------------+
| example  | Example User | example      | example,testing | testing2      | 1           | 2018-07-30 |
+----------+--------------+--------------+-----------------+---------------+-------------+------------+
Rows: 1
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_user (1)
.BR csv2_user_add (1)
.BR csv2_user_delete (1)
.BR csv2_user_update (1)
