.so ../man/_header.so
\fBcloudscheduler alias list\fR \- list aliases for the current CSV2 group:
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B alias
.B list
.BI mandatory_parameters
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_alias_list.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_none.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
List all defined aliases for the current group:

.EX
$ cloudscheduler alias list 
Server: dev, Active User: crlb, Active Group: testing, User's Groups: ['crlb', 'demo', 'test', 'test-dev2', 'testing']

Aliases:
+---------+------------+-------------------------+
+ Group   | Alias      | Clouds                  +
+---------+------------+-------------------------+
| testing | amazon     | amazon-east,amazon-west |
| testing | colin      | amazon-west             |
| testing | kevin-test | cloud7,cloud9,sig-test  |
| testing | new        | test                    |
+---------+------------+-------------------------+
Rows: 4
$
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_alias (1)
.BR csv2_alias_add (1)
.BR csv2_alias_update (1)
