.so ../man/_header.so
\fBcloudscheduler group list\fR \- list groups on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B group
.B list
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_group_list.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_group_name.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options_except_with.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
List all groups on the server:
.EX
$ cloudscheduler group list
Server: default, Active User: example, Active Group: example, User's Groups: ['examle', 'testing']

Groups:
+---------+-----------------+---------------------------+
+ Group   | Central Manager | Metadata Filenames        +
+---------+-----------------+---------------------------+
| example | example.ca      | None                      |
| testing | testing.ca      | example.yaml,testing.json |
+---------+-----------------+---------------------------+
Rows: 2
.EE
.TP
2.
List a specific group "example":
.EX
$ cloudscheduler group list -gn example
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

Groups:
+---------+-----------------+--------------------+
+ Group   | Central Manager | Metadata Filenames +
+---------+-----------------+--------------------+
| example | example.ca      | None               |
+---------+-----------------+--------------------+
Rows: 1
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_group (1)
.BR csv2_group_add (1)
.BR csv2_group_defaults (1)
.BR csv2_group_delete (1)
.BR csv2_group_metadata-delete (1)
.BR csv2_group_metadata-edit (1)
.BR csv2_group_metadata-list (1)
.BR csv2_group_metadata-load (1)
.BR csv2_group_metadata-save (1)
.BR csv2_group_metadata-update (1)
.BR csv2_group_update (1)
