.so ../man/_header.so
\fBcloudscheduler user\fP \- manage users on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY csv2
.B user
.I action
.IR "mandatory_parameters"
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_user.so
.\" --------------------------------------------------------------------
.SH ACTIONS
.\" --------------------------------------------------------------------
.P
For information on the parameters associated with each \fBuser\fP action, refer
to the documentation for that action (eg. \fBcloudscheduler user \fIaction\fB -H\fR).
The following actions are available for the \fBuser\fP object:
.TP
.B add
.so ../man/descriptions/_user_add.so
.TP
.B delete
.so ../man/descriptions/_user_delete.so
.TP
.B list
.so ../man/descriptions/_user_list.so
.TP
.B update
.so ../man/descriptions/_user_update.so
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_user_add (1)
.BR csv2_user_delete (1)
.BR csv2_user_list (1)
.BR csv2_user_update (1)