.so ../man/_header.so
\fBcloudscheduler group metadata-edit\fR \- edit group metadata files from cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B group
.B metadata-edit
.BI \-mn " name"
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_group_metadata_edit.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Mandatory
.\" --------------------------------------------------------------------
.so ../man/_mandatory_parameters.so
.so ../man/parameters/_metadata_name.so
.\" --------------------------------------------------------------------
.SS Required
.\" --------------------------------------------------------------------
.so ../man/_required_parameters.so
.so ../man/parameters/_text_editor.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
Editing the group metadata file "example":
.EX
$ cloudscheduler group metadata-edit -mn example.yaml -te vim
group metadata file "example::example.yaml" successfully  updated.
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_group (1)
.BR csv2_group_add (1)
.BR csv2_group_defaults (1)
.BR csv2_group_delete (1)
.BR csv2_group_list (1)
.BR csv2_group_metadata-delete (1)
.BR csv2_group_metadata-list (1)
.BR csv2_group_metadata-load (1)
.BR csv2_group_metadata-save (1)
.BR csv2_group_metadata-update (1)
.BR csv2_group_update (1)
