.so ../man/_header.so
\fBcloudscheduler cloud\fR \- manage clouds on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B cloud
.I action
.I mandatory_parameters
.RI "[" "options " "...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_cloud.so
.\" --------------------------------------------------------------------
.SH ACTIONS
.\" --------------------------------------------------------------------
For information on the parameters associated with each \fBcloud\fR action, refer
to the documentation for that action (\fBcloudscheduler cloud \fIaction\fB -H\fR).
The following actions are available for the \fBcloud\fR object:
.TP
.B add
.so ../man/descriptions/_cloud_add.so
.TP
.B delete
.so ../man/descriptions/_cloud_delete.so
.TP
.B list
.so ../man/descriptions/_cloud_list.so
.TP
.B metadata-collation
.so ../man/descriptions/_cloud_metadata_collation.so
.TP
.B metadata-delete
.so ../man/descriptions/_cloud_metadata_delete.so
.TP
.B metadata-edit
.so ../man/descriptions/_cloud_metadata_edit.so
.TP
.B metadata-list
.so ../man/descriptions/_cloud_metadata_list.so
.TP
.B metadata-load
.so ../man/descriptions/_cloud_metadata_load.so
.TP
.B metadata-update
.so ../man/descriptions/_cloud_metadata_update.so
.TP
.BI status
.so ../man/descriptions/_cloud_status.so
.TP
.B update
.so ../man/descriptions/_cloud_update.so
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_cloud_add (1)
.BR csv2_cloud_delete (1)
.BR csv2_cloud_list (1)
.BR csv2_cloud_metadata-collation (1)
.BR csv2_cloud_metadata-delete (1)
.BR csv2_cloud_metadata-edit (1)
.BR csv2_cloud_metadata-list (1)
.BR csv2_cloud_metadata-load (1)
.BR csv2_cloud_metadata-save (1)
.BR csv2_cloud_metadata-update (1)
.BR csv2_cloud_status (1)
.BR csv2_cloud_update (1)
