.so ../man/_header.so
\fBcloudscheduler vm list\fR \- list VMs on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B vm
.B list
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_vm_list.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_cloud_name_vm_list.so
.so ../man/parameters/_vm_cores_vm_list.so
.so ../man/parameters/_vm_disk_vm_list.so
.so ../man/parameters/_vm_foreign_vm_list.so
.so ../man/parameters/_vm_flavor_vm_list.so
.so ../man/parameters/_vm_hosts_vm_list.so
.so ../man/parameters/_vm_ram_vm_list.so
.so ../man/parameters/_vm_status_vm_list.so
.so ../man/parameters/_vm_swap_vm_list.so
.\" --------------------------------------------------------------------
.SS Table
.\" --------------------------------------------------------------------
.so ../man/_table_options_except_with.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
List all vms in the current group:
.EX
$ cloudscheduler vm list
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

VMs: (1/5)
+---------+---------+------------------------+------+-------------------+---------+--------+-----------+
+ Group   | Cloud   | Hostname               | VMID | Authorization URL | Project | Status | Flavor ID +
+---------+---------+------------------------+------+-------------------+---------+--------+-----------+
| example | example | example--example--vm-1 | vm-1 | example.com       | example | 1      | 1         |
| example | example | example--example--vm-2 | vm-2 | example.com       | example | 5      | 1         |
+---------+---------+------------------------+------+-------------------+---------+--------+-----------+

VMs: (2/5)
+---------+---------+------------------------+------+--------------+-----------+----------------+
+ Group   | Cloud   | Hostname               | Task | Power Status | Terminate | Terminate Time +
+---------+---------+------------------------+------+--------------+-----------+----------------+
| example | example | example--example--vm-1 | 1    | 1            | 0         | None           |
| example | example | example--example--vm-2 | 2    | 1            | 0         | None           |
+---------+---------+------------------------+------+--------------+-----------+----------------+

VMs: (3/5)
+---------+---------+------------------------+---------------------+---------------------+--------+--------------+
+ Group   | Cloud   | Hostname               | Status Change Time  | Last Updated        | Flavor | Condor Slots +
+---------+---------+------------------------+---------------------+---------------------+--------+--------------+
| example | example | example--example--vm-1 | 2018-08-23 00:00:00 | 2018-08-23 00:00:00 | s8     | None         |
| example | example | example--example--vm-2 | 2018-08-23 00:00:00 | 2018-08-23 00:00:00 | s8     | None         |
+---------+---------+------------------------+---------------------+---------------------+--------+--------------+

VMs: (4/5)
+---------+---------+------------------------+---------+-------+------------+-----------+------------+
+ Group   | Cloud   | Hostname               | Foreign | cores | Disk (GBs) | Ram (MBs) | Swap (GBs) +
+---------+---------+------------------------+---------+-------+------------+-----------+------------+
| example | example | example--example--vm-1 | 0       | 1     | 5          | 1000      | 0          |
| example | example | example--example--vm-2 | 0       | 1     | 5          | 1000      | 0          |
+---------+---------+------------------------+---------+-------+------------+-----------+------------+

VMs: (5/5)
+---------+---------+------------------------+---------------+----------------+
+ Group   | Cloud   | Hostname               | Poller Status | Manual_Control +
+---------+---------+------------------------+---------------+----------------+
| example | example | example--example--vm-1 | running       | 0              |
| example | example | example--example--vm-2 | error         | 0              |
+---------+---------+------------------------+---------------+----------------+
Rows: 2
.EE
.TP
2.
List only vms in the cloud "example" that are running:
.EX
$ cloudscheduler vm list -cn example -vS running
Server: default, Active User: example, Active Group: example, User's Groups: ['example', 'testing']

VMs: (1/5)
+---------+---------+------------------------+------+-------------------+---------+--------+-----------+
+ Group   | Cloud   | Hostname               | VMID | Authorization URL | Project | Status | Flavor ID +
+---------+---------+------------------------+------+-------------------+---------+--------+-----------+
| example | example | example--example--vm-1 | vm-1 | example.com       | example | 1      | 1         |
+---------+---------+------------------------+------+-------------------+---------+--------+-----------+

VMs: (2/5)
+---------+---------+------------------------+------+--------------+-----------+----------------+
+ Group   | Cloud   | Hostname               | Task | Power Status | Terminate | Terminate Time +
+---------+---------+------------------------+------+--------------+-----------+----------------+
| example | example | example--example--vm-1 | 1    | 1            | 0         | None           |
+---------+---------+------------------------+------+--------------+-----------+----------------+

VMs: (3/5)
+---------+---------+------------------------+---------------------+---------------------+--------+--------------+
+ Group   | Cloud   | Hostname               | Status Change Time  | Last Updated        | Flavor | Condor Slots +
+---------+---------+------------------------+---------------------+---------------------+--------+--------------+
| example | example | example--example--vm-1 | 2018-08-23 00:00:00 | 2018-08-23 00:00:00 | s8     | None         |
+---------+---------+------------------------+---------------------+---------------------+--------+--------------+

VMs: (4/5)
+---------+---------+------------------------+---------+-------+------------+-----------+------------+
+ Group   | Cloud   | Hostname               | Foreign | cores | Disk (GBs) | Ram (MBs) | Swap (GBs) +
+---------+---------+------------------------+---------+-------+------------+-----------+------------+
| example | example | example--example--vm-1 | 0       | 1     | 5          | 1000      | 0          |
+---------+---------+------------------------+---------+-------+------------+-----------+------------+

VMs: (5/5)
+---------+---------+------------------------+---------------+----------------+
+ Group   | Cloud   | Hostname               | Poller Status | Manual_Control +
+---------+---------+------------------------+---------------+----------------+
| example | example | example--example--vm-1 | running       | 0              |
+---------+---------+------------------------+---------------+----------------+
Rows: 1
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_vm (1)
.BR csv2_vm_update (1)
