.so ../man/_header.so
\fBcloudscheduler alias\fR \- manage cloud aliases for the current group.
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B alias
.I action
.I mandatory_parameters
.RI "[" "options " "...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_alias.so
.\" --------------------------------------------------------------------
.SH ACTIONS
.\" --------------------------------------------------------------------
For information on the parameters associated with each \fBalias\fR action, refer
to the documentation for that action (\fBcloudscheduler alias \fIaction\fB -H\fR).
The following actions are available for the \fBalias\fR object:
.TP
.B add
.so ../man/descriptions/_alias_add.so
.TP
.B list
.so ../man/descriptions/_alias_list.so
.TP
.B update
.so ../man/descriptions/_alias_update.so
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_alias_add (1)
.BR csv2_alias_list (1)
.BR csv2_alias_update (1)
