#!/bin/bash
  PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

  cmd=`basename $0`
  logfile="/root/ansible_script_logs/$cmd"

  rc=0

  private_interface=$1

  # no parameters

  echo `date` "Running $0" > ${logfile}.partial_log 2>&1

  if [ -e /etc/sysconfig/yum-autoupdate ]; then
    echo -e "\n1. sed -i 's/ENABLED=true/ENABLED=false/' /etc/sysconfig/yum-autoupdate" >>${logfile}.partial_log
    sed -i 's/ENABLED="true"/ENABLED="false"/' /etc/sysconfig/yum-autoupdate \
        >>${logfile}.partial_log 2>&1 \
        || rc=1
  fi

  if [ -e /etc/yum/yum-cron.conf ]; then
    echo -e "\n2. sed -i '/apply_updates/ s/yes/no/' /etc/yum/yum-cron.conf" >>${logfile}.partial_log
    sed -i '/apply_updates/ s/yes/no/' /etc/yum/yum-cron.conf \
        >>${logfile}.partial_log 2>&1 \
        || rc=1
  fi

  if [ -e /etc/yum/yum-cron-hourly.conf ]; then
    echo -e "\n3. sed -i '/apply_updates/ s/yes/no/' /etc/yum/yum-cron-hourly.conf" >>${logfile}.partial_log
    sed -i '/apply_updates/ s/yes/no/' /etc/yum/yum-cron-hourly.conf \
        >>${logfile}.partial_log 2>&1 \
        || rc=1
  fi

  if [ $rc == 0 ]; then 
      mv ${logfile}.partial_log ${logfile}.log
  else
      echo "WARNING: script failure, see ${logfile}.partial_log"
      exit 1
  fi
