#!/bin/bash
  /usr/sbin/ifdown-original $1 $2     

  if [ -f /etc/sysconfig/network-scripts/ifcfg-${1}.old ]; then
    mv /etc/sysconfig/network-scripts/ifcfg-${1}.old /etc/sysconfig/network-scripts/ifcfg-${1}
  fi
