---
# file: define_volumes.yaml - installs the configuration file, creates and mounts filesystems.

- name: install packages required by volume configuration
  yum:
    name: ['pciutils']
    state: latest

- name: install the volume configuration file
  template: src=ansible_volumes.j2 dest=/usr/local/etc/ansible_volumes owner=root group=root mode=0644

- name: configure volumes
  volume_configuration: config=/usr/local/etc/ansible_volumes

