#!/bin/bash
#
# chkconfig: 345 70 30
# description: deamon for condor remote procedures
# processname: csv2-htc-agent

# Source function library.
. /etc/init.d/functions
PATH=/bin:/sbin/:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

exec="$(which csv2_htc_agent)"
config="/etc/csv2_htc_agent.conf"
pidfile="/tmp/csv2_htc_agent.pid"
user=condor

start() {
    echo "Starting csv2 condor-RPC client"
    logfile=$(grep log_file $config|cut -d: -f2)
    mkdir -p $(dirname $logfile)
    touch $logfile
    chown $user $logfile
    daemon --user $user --pidfile $pidfile "$exec $config & "
    return $?
}

stop() {
    echo "Stopping csv2 condor RPC client"
    pid=$(cat $pidfile)
    kill $pid
    return $?
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    echo status
    ;;
    restart)
    stop
    start
    ;;
    reload)
    echo relaod
    ;;
    *)
    echo "Usage: csv2-htc-agent {start|stop|status|reload|restart}"
    exit 1
    ;;
esac
exit $?

