#!/bin/bash
#
# chkconfig: 345 70 30
# description: deamon for condor remote procedures
# processname: csv2-htc-agent

# Source function library.
. /etc/init.d/functions
PATH=/usr/local/sbin:/sbin:/usr/sbin:/usr/local/bin:/bin:/usr/bin

exec="$(which csv2_htc_agent)"
config="/usr/local/etc/csv2_htc_agent.conf"
pidfile="/tmp/csv2_htc_agent.pid"
user=__condor_user__

start() {
    echo "Starting csv2 condor-RPC client"
    daemon --user $user --pidfile $pidfile "$exec $config & "
    return $?
}

stop() {
    echo "Stopping csv2 condor RPC client"
    pid=$(cat $pidfile)
    kill $pid
    return $?
}

status() {
 local running=0
 running=$(ps -NC grep xf|grep -c $exec)
 if [ $running -eq 1 ];
 then 
   echo "csv2_htc_agent is running..."
 elif [ $running -gt 1 ];
 then 
  echo "There are too many csv2_htc_agents running..."
 else
   echo "csv2_htc_agent is not running..."
 fi
}

case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    status
    ;;
    restart)
    stop
    start
    ;;
    *)
    echo "Usage: csv2-htc-agent {start|stop|status|restart}"
    exit 1
    ;;
esac
exit $?

