.so ../man/_header.so
\fBcloudscheduler user update\fR \- update users on cloudscheduler version 2 (csv2) servers
.\" --------------------------------------------------------------------
.SH SYNOPSIS
.\" --------------------------------------------------------------------
.SY cloudscheduler
.B user
.B update
.BI "-un " "username"
.RI "[" "options" " ...]"
.YS
.\" --------------------------------------------------------------------
.SH DESCRIPTION
.\" --------------------------------------------------------------------
.so ../man/descriptions/_user_update.so
.\" --------------------------------------------------------------------
.SH OPTIONS
.\" --------------------------------------------------------------------
.\" --------------------------------------------------------------------
.SS Mandatory
.\" --------------------------------------------------------------------
.so ../man/_mandatory_parameters.so
.so ../man/parameters/_username_user_update.so
.\" --------------------------------------------------------------------
.SS Optional
.\" --------------------------------------------------------------------
.so ../man/_options.so
.so ../man/parameters/_group_name_user_update.so
.so ../man/parameters/_group_option.so
.so ../man/parameters/_super_user.so
.so ../man/parameters/_user_common_name.so
.so ../man/parameters/_user_password.so
.\" --------------------------------------------------------------------
.SS Global
.\" --------------------------------------------------------------------
.so ../man/_global_options.so
.\" --------------------------------------------------------------------
.SH EXAMPLES
.\" --------------------------------------------------------------------
.TP
1.
Updating a user to be a super user:
.EX
$ cloudscheduler user update -un example -SU yes
user "example" successfully updated.
.EE
.TP
2.
Adding a user to groups:
.EX
$ cloudscheduler user update -un example -gn group1,group2
user "example" successfully updated.
.EE
.TP
3.
Removing the user from a group:
.EX
$ cloudscheduler user update -un example -gn group1 -go delete
user "example" successfully updated.
.EE
.\" --------------------------------------------------------------------
.SH SEE ALSO
.\" --------------------------------------------------------------------
.BR csv2 (1)
.BR csv2_user (1)
.BR csv2_user_add (1)
.BR csv2_user_delete (1)
.BR csv2_user_list (1)
