Universe   = vanilla
Executable = try.sh
Arguments  = 4 10
dir           = /opt/cloudscheduler/condor_data_collectors/tests/job_submitter/logs
output        = $(dir)/$(Cluster).$(Process).out
error         = $(dir)/$(Cluster).$(Process).err
log           = $(dir)/$(Cluster).$(Process).log
request_disk = 1 GB
priority       = 10
Requirements = TARGET.Arch == "x86_64"
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

+VMType = "belle-worker"
+VMCPUArch = "x86_64"
+VMName = "belle-worker"
+VMAMI = "chameleon:ucernvm-prod.2.4-6.hdd,dair-qc:uCernVM-prod.2.4-6.hdd,dair-ab:uCernVM-prod.1.18-2,ecloud:ami-00000386,cc-west:ucernvm-prod.2.4-6.hdd,cc-east:ucernvm-prod.2.4-6.hdd,mouse:ucernvm-prod.2.4-6.hdd,amazon-west:ami-aab147ca,amazon2:ami-aab147ca,amazon-east:ami-7e9a8714,cybera-c:ucernvm-prod.2.4-6.hdd,azure:cernvm,beaver:centos6_condor_worker"
+VMMem = "1000"
+VMCPUCores = "1"
+VMStorage = "80"
+VMInstanceType = "mouse:m1.xlarge,alto:m1.xlarge,chameleon:m1.large,ecloud:m1.large,dair-ab:m1.xlarge,dair-qc:m1.xlarge,quicksilver:m1.medium,frank:m1.medium,google_atlas:n1-highcpu-8,cc-west:c8-30gb-186,cc-east:c8-30gb-430,amazon-west:c3.xlarge,amazon2:c3.xlarge,amazon-east:c3.xlarge,cybera-c:m1.hepnet,azure:Standard_D4_v2,beaver:s1,lrz-amazon:m8"
+VMMaximumPrice = "0.10"
+VMAMIConfig = "/srv/userdata/benchmark.yaml:cloud-config,/srv/userdata/verifycs.yaml:cloud-config,/srv/userdata/cernvm-data.txt:ucernvm-config"
+VMInjectCA = False
+TargetClouds = "beaver"

queue 5

